"""Predict complexity from aligned fMRI rows using locally trained artifacts."""

from __future__ import annotations

import argparse
import csv
import json
import pickle
from pathlib import Path

import numpy as np
import torch

from route_b.constants import COCO_SEARCH18_CATEGORIES, NSD_SUBJECTS, ROI_TIER_LABELS
from route_b.evaluation.metrics import _build_eval_model
from route_b.types import Array


def predict(
  checkpoint_path: Path, pca: Path, nsd: Path, subject: str, lh: Array, rh: Array, tasks: list[str],
  clip_text: Path, fold: int = 1, device: str = 'cpu',
) -> tuple[Array, Array]:
  """Predict one target per row from a specific fold, without image features.

  :param lh: Left hemisphere rows in Algonauts challenge vertex order.
  :param rh: Right hemisphere rows aligned with ``lh``.
  :param tasks: One supported target name for each fMRI row.
  :param pca: Local preprocessing directory generated by the training pipeline.
  :returns: Full complexity predictions and predicted standard deviations.
  """
  if lh.ndim != 2 or rh.ndim != 2 or len(lh) != len(rh) or len(tasks) != len(lh):
    raise ValueError('Hemisphere arrays and target list must have the same number of rows')
  if not len(tasks) or any(task not in COCO_SEARCH18_CATEGORIES for task in tasks):
    raise ValueError('Supply at least one row and supported COCO-Search18 targets')
  fmri = np.concatenate([lh, rh], axis=1)
  masks = np.concatenate([np.load(nsd / subject / f'roi_masks/{hemi}.streams_challenge_space.npy') for hemi in ('lh', 'rh')])
  if fmri.shape[1] != len(masks):
    raise ValueError('fMRI vertex count does not match the subject ROI masks')
  with (pca / f'{subject}_pca_models.pkl').open('rb') as stream:
    models = pickle.load(stream)
  transformed = np.concatenate([models[tier].transform(fmri[:, np.isin(masks, labels)]).astype(np.float32)
                                for tier, labels in ROI_TIER_LABELS.items()], axis=1)
  training_rows = np.load(pca / f'{subject}_pca_fmri.npy')
  transformed = (transformed - training_rows.mean(axis=0)) / (training_rows.std(axis=0) + 1e-6)
  del training_rows
  with np.load(clip_text) as embeddings:
    text = np.stack([embeddings[task] for task in tasks]).astype(np.float32)
  checkpoint = torch.load(checkpoint_path, map_location='cpu', weights_only=False, mmap=True)
  if fold < 1 or fold > len(checkpoint['fold_state_dicts']):
    raise ValueError('Fold must be between 1 and 5')
  model = _build_eval_model(transformed.shape[1], device)
  model.load_state_dict(checkpoint['fold_state_dicts'][fold - 1])
  model.eval()
  predictions, sigmas = [], []
  with torch.no_grad():
    for start in range(0, len(tasks), 256):
      selected = tasks[start:start + 256]
      mean, log_variance, _ = model(torch.from_numpy(transformed[start:start + 256]).to(device),
        torch.full((len(selected),), NSD_SUBJECTS.index(subject), dtype=torch.long, device=device),
        torch.tensor([COCO_SEARCH18_CATEGORIES.index(task) for task in selected], device=device),
        torch.from_numpy(text[start:start + 256]).to(device))
      predictions.append(mean.cpu().numpy() + np.asarray([checkpoint['category_means'][task] for task in selected]))
      sigmas.append(np.exp(.5 * log_variance.cpu().numpy()))
  return np.concatenate(predictions), np.concatenate(sigmas)


def main() -> None:
  parser = argparse.ArgumentParser(description=__doc__)
  for name in ('checkpoint', 'pca', 'nsd', 'lh', 'rh', 'tasks', 'clip-text', 'output'):
    parser.add_argument('--' + name, type=Path, required=True)
  parser.add_argument('--subject', choices=NSD_SUBJECTS, required=True)
  parser.add_argument('--fold', type=int, default=1)
  parser.add_argument('--device', default='cpu')
  args = parser.parse_args()
  tasks = json.loads(args.tasks.read_text())
  values, sigmas = predict(args.checkpoint, args.pca, args.nsd, args.subject, np.load(args.lh), np.load(args.rh), tasks,
                           args.clip_text, args.fold, args.device)
  args.output.parent.mkdir(parents=True, exist_ok=True)
  with args.output.open('w') as stream:
    writer = csv.writer(stream)
    writer.writerow(['row', 'subject', 'target', 'fold', 'complexity', 'sigma'])
    writer.writerows((i, args.subject, task, args.fold, value, sigma)
                    for i, (task, value, sigma) in enumerate(zip(tasks, values, sigmas, strict=True)))


if __name__ == '__main__':
  main()
